onboarding = false

[theme]
auto_switch = true
light_name = "gruvbox light"
dark_name = "gruvbox"

[ui]
copy_on_select = false
# mouse_capture = false
# sidebar_position = "right"
sidebar_collapsed_mode = "hidden"
status_indicators = "symbols"
tab_bar_position = "bottom"

[ui.sound]
enabled = true

[ui.toast]
delivery = "system"
